name: Build and test

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Tests
      run: dotnet test
      env:
        DIGIZUITE_API_URL: ${{ secrets.DIGIZUITE_API_URL }}
        DIGIZUITE_USERNAME: ${{ secrets.DIGIZUITE_USERNAME }}
        DIGIZUITE_PASSWORD: ${{ secrets.DIGIZUITE_PASSWORD }}
  build:
    name: Build core on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build Release
      run: dotnet build --configuration Release
  